# Generated by Django 2.1.4 on 2018-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='integer',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='product',
            name='total_peices',
            field=models.IntegerField(default=True),
        ),
    ]
