# Generated by Django 2.1.4 on 2018-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20181206_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_peices',
            new_name='peices',
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
