# Generated by Django 2.1.4 on 2018-12-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20181206_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
