# Generated by Django 2.1.4 on 2018-12-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20181206_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
    ]
