# Generated by Django 2.1.4 on 2018-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20181207_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='total',
            field=models.IntegerField(default=True),
        ),
    ]
