# Generated by Django 2.1.4 on 2018-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_piece_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=True),
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
