# Generated by Django 2.1.4 on 2018-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
