# Generated by Django 2.1.4 on 2018-12-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_direct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
