# Generated by Django 2.1.4 on 2018-12-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_auto_20181219_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total2',
        ),
        migrations.AddField(
            model_name='direct',
            name='discount2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='name2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='price2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bill.Category'),
        ),
    ]
