# Generated by Django 2.1.4 on 2018-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_auto_20181219_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='type2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
