# Generated by Django 2.1.4 on 2018-12-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_direct_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='meters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='direct',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
