# Generated by Django 2.1.4 on 2018-12-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0022_auto_20181222_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direct',
            name='meters2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
