# Generated by Django 2.1.4 on 2018-12-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0025_auto_20181222_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='discount3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='discount4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='discount5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='meters3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='meters4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='meters5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='price3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='price4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='price5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='type3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='type4',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='direct',
            name='type5',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
