# Generated by Django 2.1.4 on 2018-12-27 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0026_auto_20181223_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
