# Generated by Django 2.1.4 on 2018-12-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_auto_20181229_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
